const Groq = require("groq-sdk");
require("dotenv").config(); // Ensure env vars are loaded

// Groq connection setup
// API Key automatically picked from process.env.GROQ_API_KEY
const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY 
});

class AIInterviewEngine {
  
  async generateQuestions(cvData, field) {
    // Model: 'llama3-8b-8192' is super fast (Best for Demo)
    const MODEL_NAME = "llama-3.3-70b-versatile";
    
    console.log(`🚀 AI Engine (Groq): Generating VERBAL questions for '${field}' using ${MODEL_NAME}...`);

    const systemPrompt = `
      You are a senior technical interviewer conducting a VIDEO interview.
      Analyze the candidate's Resume and Target Field.
      Generate exactly 5 technical interview questions.

      STRICT RULES (CRITICAL):
      1. NO CODING TASKS: Do NOT ask the candidate to "write code", "implement a function", or "type a program".
      2. VERBAL ANSWERS ONLY: Ask questions that test logic, concepts, architecture, and problem-solving skills verbally.
         - Instead of "Write a function to reverse a string", ask "How would you logically reverse a string in memory?".
         - Instead of "Implement a database schema", ask "How would you design the database relations for this app?".
      3. Resume-Based: If projects exist, ask about design decisions, challenges, and "why" they chose specific tools.
      4. Field-Based: If the resume is weak, ask conceptual questions about ${field}.

      REQUIRED JSON OUTPUT FORMAT:
      Return a raw JSON object with a "questions" array. Each object MUST have:
      - "id": Integer (1 to 5)
      - "question": Short title (e.g., "React Virtual DOM")
      - "description": A 1-sentence question asking for a verbal explanation (e.g., "Explain how the Virtual DOM improves performance compared to direct DOM manipulation.")
    `;

    // Resume Data ko String mein convert
    const userPrompt = `
      CANDIDATE DATA:
      ${JSON.stringify(cvData)}

      TARGET FIELD:
      ${field}

      STRICT OUTPUT EXAMPLE (VERBAL ONLY):
      {
        "questions": [
          {
            "id": 1,
            "question": "API Security",
            "description": "Verbally explain how you would secure a REST API against common attacks like SQL Injection."
          },
          {
            "id": 2,
            "question": "State Management Logic",
            "description": "Describe the difference between Redux and Context API, and when you would choose one over the other."
          }
        ]
      }
    `;

    try {
      // 👇 Groq API Call (Instead of Ollama)
      const completion = await groq.chat.completions.create({
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
        model: MODEL_NAME,
        temperature: 0.6,
        // ✨ Critical: Ye ensure karta hai ke Groq valid JSON hi return kare
        response_format: { type: "json_object" } 
      });

      // Groq response structure
      const responseContent = completion.choices[0]?.message?.content;
      
      // JSON Parse karein
      const content = JSON.parse(responseContent || "{}");
      
      console.log("✅ Questions Generated by Groq (Fast!)");
      return content.questions; 

    } catch (error) {
      console.error("❌ Groq Generation Failed:", error);
      
      // Fallback: Agar Internet issue ho ya API limit cross ho jaye
      return [
        { 
          id: 1, 
          question: "Introduction", 
          description: "Please introduce yourself and highlight your key technical skills." 
        },
        { 
          id: 2, 
          question: "Project Challenge", 
          description: "Describe the most difficult bug you faced in a recent project and how you solved it." 
        },
        { 
          id: 3, 
          question: `Core Concepts of ${field}`, 
          description: `Can you explain a complex concept in ${field} in simple terms?` 
        },
        { 
          id: 4, 
          question: "System Design", 
          description: "How would you approach designing a scalable architecture for a high-traffic application?" 
        },
        { 
          id: 5, 
          question: "Learning Adaptability", 
          description: "Tell me about a time you had to learn a new technology quickly to meet a deadline." 
        }
      ];
    }
  }
}

module.exports = new AIInterviewEngine();